name: hoarder
version: '${version}'

main: me.sekc.hoarder.Hoarder
api-version: '26.1.2'
load: POSTWORLD

softdepend: [ PlaceholderAPI ]

authors: [ sekc ]

permissions:
  hoarder.admin:
    description: Allows admins to configure hoarder.
    default: op
  hoarder.gui:
    description: Allows player to open the hoarder gui.
    default: true